# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_search_site_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='site_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
