# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170908_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='site_name',
            field=models.CharField(max_length=300),
        ),
    ]
