# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170908_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=300, null=True)),
                ('site_url', models.CharField(max_length=2000)),
                ('site_email', models.CharField(blank=True, max_length=300, null=True)),
                ('site_address', models.CharField(blank=True, max_length=500, null=True)),
                ('site_contact_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('search_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='infosearch',
            name='site_keywords',
            field=models.ManyToManyField(blank=True, to='main.Keyword'),
        ),
        migrations.AddField(
            model_name='infosearch',
            name='site_phones',
            field=models.ManyToManyField(blank=True, to='main.Phone'),
        ),
    ]
