# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171005_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoYellow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300)),
                ('site_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('site_email', models.CharField(blank=True, max_length=300, null=True)),
                ('site_address', models.CharField(blank=True, max_length=500, null=True)),
                ('site_phone', models.ManyToManyField(blank=True, to='main.Phone')),
            ],
        ),
    ]
