# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_infoyellow'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoyellow',
            name='search_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
