# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_infoyellow_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosearch',
            name='site_url',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='infoyellow',
            name='site_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
