# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171227_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosearch',
            name='average_ranking',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
