# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180118_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosearch',
            name='search_nums',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
